### ISSUE TITLE
DQL = C rows not being removed 20220119

### ISSUE THREAD

**Issue by SteveHansonODEQ** [OR-Dept-Environmental-Quality/odeqcdr#28]
https://github.com/OR-Dept-Environmental-Quality/odeqcdr/blob/4177a98d7bd8f50aec398219eb74333ba8037066/R/sumstats.R#L36

In testing on 1/19/22 on TMDL MP datasets the C data results are not being deleted (tmdl data is assigned a DQL but status kind of ignored until translated from DQL in AWQMS as defined outside of this script in import configuration file) . If I separate out the piped exclusions and do Status.ID and rDQL on separate lines then it behaves as expected. Not removing these C data results cascades to problems with when there are valid data and what the hour's DQL should be.

I'll email the result file that gets loaded into this part of the script ResultsTest20220119.Rdata

**Comment by DEQrmichie** [comment]
Addressed in eca6475
